micronaut:
  application:
    name: orangeTalents03TemplatePixKeymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keymanagerGrpcServer:
      address: '${KEYMANAGER_GRPC_SERVER:`localhost:50051`}'
      plaintext: true
      max-retry-attempts: 5